name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-vue-mess-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vue-mess-detector
          path: ./dist

  test-vue-mess-detector:
    runs-on: ${{ matrix.platform }}
    needs: build-vue-mess-detector

    strategy:
      matrix:
        platform: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        package-manager: [ npm, yarn, pnpm, bun ]

    name: Testing with ${{ matrix.package-manager }} on ${{ matrix.platform }}
    steps:
      - name: Create package directory
        run: mkdir ./package

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vue-mess-detector
          path: ./package

      - name: Create test-repo directory
        run: mkdir ./test-repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check PNPM
        if: matrix.package-manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: '9.9.0'

      - name: Check Yarn
        if: matrix.package-manager == 'yarn'
        run: npm install -g yarn

      - name: Check Bun
        if: matrix.package-manager == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.26'

      - name: Create Vue Project (Linux/Mac)
        if: runner.os != 'Windows'
        working-directory: ./test-repo
        run: |
          if [ "${{ matrix.package-manager }}" == "pnpm" ]; then
            yes "my-package" | head -n 1 | pnpm create vue@latest . --default --typescript
            pnpm install
          elif [ "${{ matrix.package-manager }}" == "yarn" ]; then
            yes "my-package" | head -n 1 | yarn --cwd . create vue . --default --typescript
            yarn install
          elif [ "${{ matrix.package-manager }}" == "bun" ]; then
            yes "my-package" | head -n 1 | bun create vue . --default --typescript --cwd=. --ignore-scripts
            bun install --ignore-scripts
          else
            yes "my-package" | head -n 1 | npm create vue@latest -- . --default --typescript
            npm install
          fi

      - name: Create Vue Project (Windows)
        if: runner.os == 'Windows'
        working-directory: ./test-repo
        run: |
          if ($Env:matrix_package_manager -eq 'pnpm') {
            echo "my-package" | pnpm create vue@latest . --default --typescript
            pnpm install
          } elseif ($Env:matrix_package_manager -eq 'yarn') {
            echo "my-package" | yarn create vue . --default --typescript
            yarn install
          } elseif ($Env:matrix_package_manager -eq 'bun') {
            echo "my-package" | bun create vue . --default --typescript --ignore-scripts
            bun install --ignore-scripts
          } else {
            echo "my-package" | npm create vue@latest -- . --default --typescript
            npm install
          }

      - name: Run Vue Mess Detector (Linux/Mac)
        if: runner.os != 'Windows'
        working-directory: ./test-repo
        run: |
          if [ "${{ matrix.package-manager }}" == "pnpm" ]; then
              pnpm add file:../package/vue-mess-detector-*.tgz -D
              pnpm vue-mess-detector analyze
          elif [ "${{ matrix.package-manager }}" == "yarn" ]; then
              yarn add file:../package/vue-mess-detector-*.tgz -D
              yarn vue-mess-detector analyze
          elif [ "${{ matrix.package-manager }}" == "bun" ]; then
              bun add file:../package/vue-mess-detector-*.tgz --dev
              bunx vue-mess-detector analyze
          else
              npm install file:../package/vue-mess-detector-*.tgz --save-dev
              npx vue-mess-detector analyze
          fi

      - name: Run Vue Mess Detector (Windows)
        if: runner.os == 'Windows'
        working-directory: ./test-repo
        run: |
          if ($Env:matrix_package_manager -eq 'pnpm') {
              pnpm add file:../package/vue-mess-detector-*.tgz -D
              pnpm vue-mess-detector analyze
          } elseif ($Env:matrix_package_manager -eq 'yarn') {
              yarn add file:../package/vue-mess-detector-*.tgz -D
              yarn vue-mess-detector analyze
          } elseif ($Env:matrix_package_manager -eq 'bun') {
            bun add file:../package/vue-mess-detector-*.tgz --dev
            bunx vue-mess-detector analyze
          } else {
            npm install file:../package/vue-mess-detector-*.tgz --save-dev
            npx vue-mess-detector analyze
          }
